CUDNN:
  BENCHMARK: true
  DETERMINISTIC: false
  ENABLED: true
BACKBONE_MODEL: 'pose_hrnet'
MODEL: 'multi_person_posenet'
DATA_DIR: ''
GPUS: '0'
OUTPUT_DIR: 'HRNET_SERVER_HICT_6x10x2'
LOG_DIR: 'log_HRNET_ASSO'
# WORKERS: 4
WORKERS: 4
PRINT_FREQ: 1000

DATASET:
  COLOR_RGB: True
  TRAIN_DATASET: 'panoptic'
  TEST_DATASET: 'panoptic'
  DATA_FORMAT: jpg
  DATA_AUGMENTATION: False
  FLIP: False
#   ROOT: 'data/panoptic-toolbox/data/' # 'data/panoptic/'
  ROOT: '/datasets/panoptic-toolbox_comp/data/' # 'data/panoptic/'
  ROT_FACTOR: 45
  SCALE_FACTOR: 0.35
  TEST_SUBSET: 'validation'
  TRAIN_SUBSET: 'train'
  ROOTIDX: 2
  CAMERA_NUM: 5
  # yk experiments.
  FOCAL_LENGTH_AUGMENTATION: True
  GRID_ZROTATION_AUGMENTATION: True
  SPACE_XYTRANSLATION_AUGMENTATION: True
NETWORK:
  PRETRAINED_BACKBONE: "" # yk indicated path directly. check pose_resnet
  PRETRAINED:  "/workspace/voxelpose_HICT/data/model_best_6x10x2_epoch1_pth.tar"  # 'null'
  TARGET_TYPE: gaussian
  IMAGE_SIZE:
  - 960
  - 512
#   HEATMAP_SIZE:
#   - 240
#   - 128
  HEATMAP_SIZE:
  - 480
  - 256
  SIGMA: 3
  NUM_JOINTS: 15
  USE_GT: False
POSE_RESNET:
  FINAL_CONV_KERNEL: 1
  DECONV_WITH_BIAS: False
  NUM_DECONV_LAYERS: 3
  NUM_DECONV_FILTERS:
  - 256
  - 256
  - 256
  NUM_DECONV_KERNELS:
  - 4
  - 4
  - 4
  NUM_LAYERS: 50
LOSS:
  USE_TARGET_WEIGHT: true
TRAIN:
  BATCH_SIZE: 1
  SHUFFLE: true
  BEGIN_EPOCH: 0
  END_EPOCH: 10
  RESUME: true
  OPTIMIZER: adam
  LR: 0.0001
TEST:
  MODEL_FILE: 'model_best.pth.tar'
  # originally 4, aug_yk force it 1. need to be fixed.
  BATCH_SIZE: 1
DEBUG:
  DEBUG: true
  SAVE_HEATMAPS_GT: false
  SAVE_HEATMAPS_PRED: false
MULTI_PERSON:
  SPACE_SIZE:
    - 6000.0
    - 10000.0
    - 2000.0
  SPACE_CENTER:
    - 0.0 # 120.0 # 0.0, 0.0 CENTER NESSESARY BECAUSE ROOT_SPACE ROTATION AUG IMPLEMENTED.
    - 0.0 # -500.0 # -600.0
    - 800.0
  INITIAL_CUBE_SIZE:
    - 60
    - 100
    - 20
  MAX_PEOPLE_NUM: 10
  THRESHOLD: 0.3
PICT_STRUCT:
  GRID_SIZE:
    - 2000.0
    - 2000.0
    - 2000.0
  CUBE_SIZE:
    - 64
    - 64
    - 64
